In this notebook we learn about: joining, merging and concatenating in pandas

In [1]:
import pandas as pd
import numpy as np

In [8]:
courses=pd.read_csv('./datasets_4/courses.csv')
nov=pd.read_csv('./datasets_4/reg-month1.csv')
dec=pd.read_csv('./datasets_4/reg-month2.csv')
students=pd.read_csv('./datasets_4/students.csv')
matches=pd.read_csv('./datasets_4/matches.csv')
delivery=pd.read_csv('./datasets_3/deliveries.csv')

pd.concat: use to append dataframe either vertically or horizontally

In [12]:
pd.concat([nov,dec],axis=1) # horizonatally combined
regs=pd.concat([nov,dec]) # vertically combined

MultiIndex DataFrame

In [15]:
multiIndex=pd.concat([nov,dec],keys=['Nov','Dec'])
multiIndex.loc['Nov']

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

#### Joins

In [21]:
from IPython.display import Image
url='https://www.dofactory.com/img/sql/sql-joins.png'
Image(url=url,width=500,height=300)

inner join

In [16]:
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

In [17]:
regs

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

add student joining the course_id using student_id

In [ ]:
# we need common column to join, like students also contains student_id and regs also has student_id, so we join both of them on 'student_id' column
# inner join: interection of set

In [22]:
students.merge(regs,how='inner',on='student_id') # phele aaya woh left table and baad wala right table
# var1.merge(var2.how='type_of_join',on='common column')

    student_id                name  partner  course_id
0            1       Kailash Harjo       23          1
1            1       Kailash Harjo       23          6
2            1       Kailash Harjo       23         10
3            1       Kailash Harjo       23          9
4            2         Esha Butala        1          5
5            3      Parveen Bhalla        3          3
6            3      Parveen Bhalla        3          5
7            7        Tarun Thaker        9          8
8            7        Tarun Thaker        9         10
9            7        Tarun Thaker        9          7
10           7        Tarun Thaker        9          2
11           7        Tarun Thaker        9          6
12          11  David Mukhopadhyay       20          7
13          11  David Mukhopadhyay       20          8
14          11  David Mukhopadhyay       20         10
15          12          Radha Dutt       19         10
16          12          Radha Dutt       19          1
17          12          Radha Dutt       19          5
18          12          Radha Dutt       19          7
19          13      Munni Varghese       24          3
20          14    Pranab Natarajan       22          9
21          14    Pranab Natarajan       22          6
22          14    Pranab Natarajan       22          4
23          14    Pranab Natarajan       22          1
24          15           Preet Sha       16          5
25          15           Preet Sha       16          1
26          16        Elias Dodiya       25          9
27          16        Elias Dodiya       25          5
28          16        Elias Dodiya       25          7
29          16        Elias Dodiya       25          3
30          17        Yasmin Palan        7          7
31          17        Yasmin Palan        7         10
32          18     Fardeen Mahabir       13          6
33          18     Fardeen Mahabir       13          1
34          18     Fardeen Mahabir       13          8
35          19        Qabeel Raman       12          4
36          19        Qabeel Raman       12          2
37          21          Seema Kota       15          1
38          22          Yash Sethi       21          3
39          22          Yash Sethi       21          5
40          22          Yash Sethi       21          6
41          23      Chhavi Lachman       18          1
42          23      Chhavi Lachman       18          4
43          23      Chhavi Lachman       18          3
44          23      Chhavi Lachman       18          6
45          23      Chhavi Lachman       18          9
46          23      Chhavi Lachman       18          5
47          24        Radhika Suri       17          4
48          25     Shashank D’Alia        2          1
49          25     Shashank D’Alia        2         10

left join

In [23]:
courses.merge(regs,how='left',on='course_id')

    course_id       course_name  price  student_id
0           1            python   2499        23.0
1           1            python   2499        18.0
2           1            python   2499         1.0
3           1            python   2499        15.0
4           1            python   2499        21.0
5           1            python   2499        25.0
6           1            python   2499        12.0
7           1            python   2499        14.0
8           1            python   2499        38.0
9           2               sql   3499        19.0
10          2               sql   3499         7.0
11          3     data analysis   4999        22.0
12          3     data analysis   4999        13.0
13          3     data analysis   4999        23.0
14          3     data analysis   4999         3.0
15          3     data analysis   4999        16.0
16          4  machine learning   9999        23.0
17          4  machine learning   9999        19.0
18          4  machine learning   9999        24.0
19          4  machine learning   9999        14.0
20          5           tableau   2499        15.0
21          5           tableau   2499        16.0
22          5           tableau   2499         3.0
23          5           tableau   2499        12.0
24          5           tableau   2499         2.0
25          5           tableau   2499        22.0
26          5           tableau   2499        23.0
27          6          power bi   1899        18.0
28          6          power bi   1899         1.0
29          6          power bi   1899        23.0
30          6          power bi   1899        14.0
31          6          power bi   1899         7.0
32          6          power bi   1899        22.0
33          7          ms sxcel   1599        11.0
34          7          ms sxcel   1599        17.0
35          7          ms sxcel   1599        16.0
36          7          ms sxcel   1599         7.0
37          7          ms sxcel   1599        12.0
38          8            pandas   1099         7.0
39          8            pandas   1099        11.0
40          8            pandas   1099        18.0
41          8            pandas   1099        50.0
42          9            plotly    699        16.0
43          9            plotly    699        14.0
44          9            plotly    699         1.0
45          9            plotly    699        23.0
46          9            plotly    699        42.0
47         10           pyspark   2499         7.0
48         10           pyspark   2499        25.0
49         10           pyspark   2499        12.0
50         10           pyspark   2499        17.0
51         10           pyspark   2499         1.0
52         10           pyspark   2499        11.0
53         11             Numpy    699         NaN
54         12               C++   1299         NaN

right join

In [27]:
temp_df=pd.DataFrame({
    'student_id':[26,27,28],
    'name':['naman','rudra','op'],
    'partner':[28,26,27]
})
temp_df
students=pd.concat([students,temp_df],ignore_index=True)
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2
25          26               naman       28
26          27               rudra       26
27          28                  op       27

In [30]:
students.merge(regs,how='right',on='student_id')

    student_id                name  partner  course_id
0           23      Chhavi Lachman     18.0          1
1           15           Preet Sha     16.0          5
2           18     Fardeen Mahabir     13.0          6
3           23      Chhavi Lachman     18.0          4
4           16        Elias Dodiya     25.0          9
5           18     Fardeen Mahabir     13.0          1
6            1       Kailash Harjo     23.0          1
7            7        Tarun Thaker      9.0          8
8           22          Yash Sethi     21.0          3
9           15           Preet Sha     16.0          1
10          19        Qabeel Raman     12.0          4
11           1       Kailash Harjo     23.0          6
12           7        Tarun Thaker      9.0         10
13          11  David Mukhopadhyay     20.0          7
14          13      Munni Varghese     24.0          3
15          24        Radhika Suri     17.0          4
16          21          Seema Kota     15.0          1
17          16        Elias Dodiya     25.0          5
18          23      Chhavi Lachman     18.0          3
19          17        Yasmin Palan      7.0          7
20          23      Chhavi Lachman     18.0          6
21          25     Shashank D’Alia      2.0          1
22          19        Qabeel Raman     12.0          2
23          25     Shashank D’Alia      2.0         10
24           3      Parveen Bhalla      3.0          3
25           3      Parveen Bhalla      3.0          5
26          16        Elias Dodiya     25.0          7
27          12          Radha Dutt     19.0         10
28          12          Radha Dutt     19.0          1
29          14    Pranab Natarajan     22.0          9
30           7        Tarun Thaker      9.0          7
31           7        Tarun Thaker      9.0          2
32          16        Elias Dodiya     25.0          3
33          17        Yasmin Palan      7.0         10
34          11  David Mukhopadhyay     20.0          8
35          14    Pranab Natarajan     22.0          6
36          12          Radha Dutt     19.0          5
37          12          Radha Dutt     19.0          7
38          18     Fardeen Mahabir     13.0          8
39           1       Kailash Harjo     23.0         10
40           1       Kailash Harjo     23.0          9
41           2         Esha Butala      1.0          5
42           7        Tarun Thaker      9.0          6
43          22          Yash Sethi     21.0          5
44          22          Yash Sethi     21.0          6
45          23      Chhavi Lachman     18.0          9
46          23      Chhavi Lachman     18.0          5
47          14    Pranab Natarajan     22.0          4
48          14    Pranab Natarajan     22.0          1
49          11  David Mukhopadhyay     20.0         10
50          42                 NaN      NaN          9
51          50                 NaN      NaN          8
52          38                 NaN      NaN          1

In [31]:
students.merge(regs,how='left',on='student_id')

    student_id                name  partner  course_id
0            1       Kailash Harjo       23        1.0
1            1       Kailash Harjo       23        6.0
2            1       Kailash Harjo       23       10.0
3            1       Kailash Harjo       23        9.0
4            2         Esha Butala        1        5.0
5            3      Parveen Bhalla        3        3.0
6            3      Parveen Bhalla        3        5.0
7            4         Marlo Dugal       14        NaN
8            5         Kusum Bahri        6        NaN
9            6  Lakshmi Contractor       10        NaN
10           7        Tarun Thaker        9        8.0
11           7        Tarun Thaker        9       10.0
12           7        Tarun Thaker        9        7.0
13           7        Tarun Thaker        9        2.0
14           7        Tarun Thaker        9        6.0
15           8      Radheshyam Dey        5        NaN
16           9   Nitika Chatterjee        4        NaN
17          10      Aayushman Sant        8        NaN
18          11  David Mukhopadhyay       20        7.0
19          11  David Mukhopadhyay       20        8.0
20          11  David Mukhopadhyay       20       10.0
21          12          Radha Dutt       19       10.0
22          12          Radha Dutt       19        1.0
23          12          Radha Dutt       19        5.0
24          12          Radha Dutt       19        7.0
25          13      Munni Varghese       24        3.0
26          14    Pranab Natarajan       22        9.0
27          14    Pranab Natarajan       22        6.0
28          14    Pranab Natarajan       22        4.0
29          14    Pranab Natarajan       22        1.0
30          15           Preet Sha       16        5.0
31          15           Preet Sha       16        1.0
32          16        Elias Dodiya       25        9.0
33          16        Elias Dodiya       25        5.0
34          16        Elias Dodiya       25        7.0
35          16        Elias Dodiya       25        3.0
36          17        Yasmin Palan        7        7.0
37          17        Yasmin Palan        7       10.0
38          18     Fardeen Mahabir       13        6.0
39          18     Fardeen Mahabir       13        1.0
40          18     Fardeen Mahabir       13        8.0
41          19        Qabeel Raman       12        4.0
42          19        Qabeel Raman       12        2.0
43          20       Hanuman Hegde       11        NaN
44          21          Seema Kota       15        1.0
45          22          Yash Sethi       21        3.0
46          22          Yash Sethi       21        5.0
47          22          Yash Sethi       21        6.0
48          23      Chhavi Lachman       18        1.0
49          23      Chhavi Lachman       18        4.0
50          23      Chhavi Lachman       18        3.0
51          23      Chhavi Lachman       18        6.0
52          23      Chhavi Lachman       18        9.0
53          23      Chhavi Lachman       18        5.0
54          24        Radhika Suri       17        4.0
55          25     Shashank D’Alia        2        1.0
56          25     Shashank D’Alia        2       10.0
57          26               naman       28        NaN
58          27               rudra       26        NaN
59          28                  op       27        NaN

outer join

In [33]:
students.merge(regs,how='outer',on='student_id').tail(10)

    student_id             name  partner  course_id
53          23   Chhavi Lachman     18.0        5.0
54          24     Radhika Suri     17.0        4.0
55          25  Shashank D’Alia      2.0        1.0
56          25  Shashank D’Alia      2.0       10.0
57          26            naman     28.0        NaN
58          27            rudra     26.0        NaN
59          28               op     27.0        NaN
60          38              NaN      NaN        1.0
61          42              NaN      NaN        9.0
62          50              NaN      NaN        8.0