#### Types of Unclean Data
There are 2 kinds of unclean data
* Dirty data (Data with Quality issues): Dirty dat, also known as low quality data.Low quality data has content issues
- Duplicated data
- Missing data
- Corrupt data
- Ineqaulity data

* Messy data(Data with tidiness issues): Messy data, also known as untidy data. untidy data has structural issues. Tidy data has the following properties:
- Each variable forms a column
- Each observation forms a row
- Each observational unit forms a table

In [1]:
# importing libraries
import pandas as pd
import numpy as np

In [2]:
# importing datasets
patients=pd.read_csv('./datasets/patients.csv')
treatments=pd.read_csv('./datasets/treatments.csv')
adverse=pd.read_csv('./datasets/adverse_reactions.csv')
treatments_cuts=pd.read_csv('./datasets/treatments_cut.csv')

Viewing datasets

In [3]:
# 1. patients
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [4]:
# 2. treatments
treatments.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [5]:
# 3. treatment cuts
treatments_cuts.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [6]:
# 4. adverse reactions
adverse.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

### <1/> Write a summary for your data

This is a dataset about 500 patients of which 350 patients participated in a clinical trial. None of the patients were using Novodra(insulin injection) or Auralin (oral tablet insulin) as their primary source of insulin before. All were experiencing elevated HbA1c levels (high blood sugar level)

All 350 patients were treated with Novodra to establis a baseline sugar level and insulin dose. After 4 weeks, which isnt enough time to capture all the change in sugar level (HbA1c) that can be attributed by the switch to Auralin or Novodra:
* 175 patients switched to Auralin for 24 weeks.
* 175 patients used Novodra for 24 weeks.

Adverse reactions is the data about the side effects of using both.

<2/> Write Column descriptions

**Table:** patients
* patient_id
* assigned_sex: male or female
* given_name: first name
* surname
* address
* city
* state
* zip_code
* contact
* birthdate
* weight(lbs)
* height
* bmi: body mass index

**Table:** treatments & treatment_cut
* given_name
* surname
* auralin: the insulin tablet
* novodra: the insulin injection
* hba1c_start: blood sugar level measurement in the beginning of treatment
* hba1c_end: blood sugar level measurement in the end of treatment
* hba1c_change: changes between start and end

**Table:** Adverse reactions
* given_name
* surname
* adverse_reaction: side effects of consumption

### <3/> Add any additional information

## Types of Assessment

There are 2 types of assessment styles:
1. Manual: looking through the data manually in google sheets
2. Programmatic: By using pandas functions such as info, describe or sample

#### Steps in Assessment
* Discover
* Document

exporting data for manual assessment

In [ ]:
with pd.ExcelWriter('clinical_trials.xlsx') as writer:
    patients.to_excel(writer,sheet_name='patients')
    treatments.to_excel(writer,sheet_name='treatments')
    treatments_cuts.to_excel(writer,sheet_name='treatments_cuts')
    adverse.to_excel(writer,sheet_name='adverse')
    
# we can also open directly using ms excel also.

#### Issues with the datset

1. Dirty Data
* Table -> `Patient`
    - patiend_id = 9 has misspelled name 'Dsvid' instead of 'David' `accuracy`
    - state col sometimes contain full name and sometimes short forms. `consistency`
    - Zip code col has entries with 4 digit , it must be 5 `validity`
    - data missing for 12 patients in these cols:address,city,state,zip_code,country,contact `completion`
    - incorrect for: assigned_sex, zip code, birthdate `validity`
    - duplicate enteries by name 'John Doe' `accuracy`
    - one patient, id=210, has weight=48.8 pounds its miscellenous `accuracy`
    - one patient, id=4, has height=27inch, which is not matching its bmi `accuracy`

* Table -> `treatment` & `treatment_cut`
    - the given_name and surname col in treatment has all lowers but patient given_name and surname col has all capital letters. `consistency`
    - remove 'u' from Auralin & Novodra cols as u represents only unit. `validity`
    - 'hyphen' in auralin & novodra col treated as nan. `validity`
    - missing values in hba1c_change col. `completeion`
    - one duplicate entry by the name 'joseph' `accuracy`
    - hba1c_change has wrong enteries as it  fills with start-end, but the enteries are false when calculating it. `accuracy`

* Table -> `adverse`
    - the given_name and surname col in adverse_reaction has all lowers but patient data has given_name and surname has all capital letters. `consistency`


2. Messy Data
* Table -> `Patient`
    - Contact col contains both phone and email together

* Table -> `treatment` & `treatment_cut`
    - Auralin & Novodra col should be split between 2 cols , start and end dose instead of hyphen

* Table -> `adverse`
    - we shouldnt this table as, it only presents one col, which can add in treatment.

#### Automatic Assessment
* head and tail
* sample
* infor
* isnull
* duplicated
* describe

In [13]:
adverse.info()

<class 'pandas.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        34 non-null     str
 1   surname           34 non-null     str
 2   adverse_reaction  34 non-null     str
dtypes: str(3)
memory usage: 948.0 bytes

In [10]:
patients[patients['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [20]:
treatments[treatments.duplicated(subset=['given_name','surname'])]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [21]:
treatments_cuts[treatments_cuts.duplicated(subset=['given_name','surname'])]

Empty DataFrame
Columns: [given_name, surname, auralin, novodra, hba1c_start, hba1c_end, hba1c_change]
Index: []

In [24]:
adverse.duplicated(subset=['given_name','surname']).sum()

np.int64(0)

In [25]:
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [26]:
# there is someone in patients data whose weight is 48.8 pounds approx. 21kg,let's check he is kid or not
patients[patients['weight'] == 48.8]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

bmi value is not matching with the height and weight so its wrong entry

In [28]:
# In patients data, minimum height is 27inch, which is 2.5 feet approx. we have to check
patients[patients['height']==27.00]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

bmi entery is not matching with the height and weight of the person that means its wrong entery

In [29]:
treatments.describe()

       hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    171.000000
mean      7.985929    7.589286      0.546023
std       0.568638    0.569672      0.279555
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.340000
50%       7.800000    7.420000      0.380000
75%       7.970000    7.570000      0.920000
max       9.950000    9.580000      0.990000

In [33]:
# max is slightly higher in treatments, so we check
treatments.sort_values('hba1c_change',na_position='first')
# not much outliers, its normal.

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
...,...,...,...,...,...,...,...
49,jackson,addison,-,42u - 42u,7.99,7.51,0.98
17,gina,cain,-,36u - 36u,7.88,7.40,0.98
138,giovana,rocha,-,23u - 21u,7.87,7.38,0.99
32,laura,ehrlichmann,-,43u - 40u,7.95,7.46,0.99
245,wu,sung,-,47u - 48u,7.61,7.12,0.99

we can clearly able to see the hba1c_change data is wrong in tail(5), wrong enteries are put

In [34]:
treatments_cuts.sort_values('hba1c_change',na_position='first')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
6,sara,miles,30u - 35u,-,7.53,7.12,NaN
7,frydryk,adamski,63u - 74u,-,7.75,7.27,NaN
8,jane,citizen,-,37u - 38u,7.98,7.60,NaN
...,...,...,...,...,...,...,...
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.95
41,dalmacia,madrid,-,26u - 23u,7.67,7.21,0.96
9,angela,lavrentyev,-,28u - 24u,7.61,7.14,0.97
42,daimy,tromp,-,40u - 45u,9.41,8.94,0.97
34,adlan,shishani,-,43u - 40u,7.84,7.37,0.97

## *Note:- Assessing Data is an Iterative Process, you cant gain things in one go.*

#### Data Quality Dimensions:-
* Completeness -> is data missing?
* Validity -> is data invalid -> negative height -> duplicate patient id
* Accuracy -> data is valid but not accurate -> weight-> 1kg
* Consistency -> both valid accurate but written differently -> New York and NY

### Order of Severity:
completeness > Validity > Accuracy > Consistency

#### ORDER:
1. Completeness
2. Tidy
3. Validity
4. Accuracy
5. Consistency

Steps Involved in Data Cleaning
* Define
* Code
* Test

## Data Cleaning

Define:
- replace all missing data

In [35]:
## patients ke kuch cols ka data missing hai
patients[patients['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [37]:
patients.fillna("No data", inplace=True)
# here fillna also not working as some columns are float with missing data

TypeError: Invalid value 'No data' for dtype 'float64'

Define
- replace all missing values of patients data with no data or wrong data
- we have to perform hba1c_change=hba1c_start-hba1c_end

In [ ]:
# missing values in hba1c_change
treatments['hba1c_change']=treatments['hba1c_start']-treatments['hba1c_end']

In [39]:
treatments

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
275,albina,zetticci,45u - 51u,-,7.93,7.73,0.20
276,john,teichelmann,-,49u - 49u,7.90,7.58,0.32
277,mathea,lillebø,23u - 36u,-,9.04,8.67,0.37
278,vallie,prince,31u - 38u,-,7.64,7.28,0.36
279,samúel,guðbrandsson,53u - 56u,-,8.00,7.64,0.36

In [40]:
# similarly for treatments_cuts
treatments_cuts['hba1c_change']=treatments_cuts['hba1c_start']-treatments_cuts['hba1c_end']
treatments_cuts

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,0.40
2,alwin,svensson,36u - 39u,-,7.78,7.34,0.44
3,thể,lương,-,61u - 64u,7.64,7.22,0.42
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38
...,...,...,...,...,...,...,...
65,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.45
67,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
68,berta,napolitani,-,42u - 44u,7.68,7.21,0.47
69,armina,sauvé,36u - 46u,-,7.86,7.40,0.46

In [41]:
treatments.info()

<class 'pandas.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    str
 1   surname       280 non-null    str
 2   auralin       280 non-null    str
 3   novodra       280 non-null    str
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  280 non-null    float64
dtypes: float64(3), str(4)
memory usage: 15.4 KB

In [42]:
treatments_cuts.info()

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     str
 1   surname       70 non-null     str
 2   auralin       70 non-null     str
 3   novodra       70 non-null     str
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  70 non-null     float64
dtypes: float64(3), str(4)
memory usage: 4.0 KB

#### Tidiness: Messy data

Define:
* patients table me contact col me phone and email dono sath me hai
* we have to seperate them out using regex email and phone

In [ ]:
# its out of our scope for now

In [71]:
# Auralin and Novodra must be in different cols for treatment, treatment_cut
treatment=pd.concat([treatments,treatments_cuts])
treatment

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
65,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.45
67,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
68,berta,napolitani,-,42u - 44u,7.68,7.21,0.47
69,armina,sauvé,36u - 46u,-,7.86,7.40,0.46

In [72]:
treatment=treatment.melt(id_vars=['given_name',	'surname', 'hba1c_start',	'hba1c_end',	'hba1c_change'],var_name='dose_type',value_name='doses')

In [73]:
treatment=treatment[treatment['doses']!='-']
treatment

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,dose_type,doses
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u - 42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u - 38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u - 36u
...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55u - 51u
690,maret,sultygov,7.67,7.30,0.37,novodra,26u - 23u
694,lixue,hsueh,9.21,8.80,0.41,novodra,22u - 23u
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u
698,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u

In [74]:
# doses are starting and ending values we have to seperate them out

treatment['dose_start']=treatment['doses'].str.split('-').str.get(0)
treatment['dose_end']=treatment['doses'].str.split('-').str.get(1)
treatment

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,dose_type,doses,dose_start,dose_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u,41u,48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u,33u,36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u - 42u,37u,42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u - 38u,31u,38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u - 36u,30u,36u
...,...,...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55u - 51u,55u,51u
690,maret,sultygov,7.67,7.30,0.37,novodra,26u - 23u,26u,23u
694,lixue,hsueh,9.21,8.80,0.41,novodra,22u - 23u,22u,23u
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u,28u,26u
698,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u,42u,44u

In [75]:
# we can also remove the u
treatment['dose_start']=treatment['dose_start'].str.replace('u','')
treatment['dose_end']=treatment['dose_end'].str.replace('u','')
treatment['dose_start']=treatment['dose_start'].astype('int')
treatment['dose_end']=treatment['dose_end'].astype('int')
treatment.info()

<class 'pandas.DataFrame'>
Index: 350 entries, 0 to 698
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    350 non-null    str
 1   surname       350 non-null    str
 2   hba1c_start   350 non-null    float64
 3   hba1c_end     350 non-null    float64
 4   hba1c_change  350 non-null    float64
 5   dose_type     350 non-null    str
 6   doses         350 non-null    str
 7   dose_start    350 non-null    int64
 8   dose_end      350 non-null    int64
dtypes: float64(3), int64(2), str(4)
memory usage: 27.3 KB

Adverse table shouldnt exist independently as its only taking more space

In [76]:
treatment=pd.merge(treatment,adverse)
treatment

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,dose_type,doses,dose_start,dose_end,adverse_reaction
0,joseph,day,7.70,7.19,0.51,auralin,29u - 36u,29,36,hypoglycemia
1,clinton,miller,7.79,7.40,0.39,auralin,42u - 51u,42,51,throat irritation
2,louise,johnson,7.63,7.32,0.31,auralin,32u - 42u,32,42,hypoglycemia
3,finley,chandler,7.65,7.26,0.39,auralin,31u - 45u,31,45,headache
4,idalia,moore,8.34,7.90,0.44,auralin,25u - 31u,25,31,hypoglycemia
5,xiuxiu,chang,7.64,7.23,0.41,auralin,32u - 41u,32,41,hypoglycemia
6,joseph,day,7.70,7.19,0.51,auralin,29u - 36u,29,36,hypoglycemia
7,gabriele,saenger,8.35,7.97,0.38,auralin,22u - 30u,22,30,hypoglycemia
8,merci,leroux,8.98,8.64,0.34,auralin,27u - 33u,27,33,hypoglycemia
9,anenechi,chidi,7.64,7.31,0.33,auralin,52u - 61u,52,61,hypoglycemia
10,manouck,wubbels,7.66,7.40,0.26,auralin,55u - 62u,55,62,throat irritation
11,jia li,teng,7.66,7.32,0.34,auralin,48u - 54u,48,54,nausea
12,alex,crawford,7.69,7.30,0.39,auralin,51u - 62u,51,62,hypoglycemia
13,flavia,fiorentino,7.95,7.60,0.35,auralin,46u - 57u,46,57,cough
14,noe,aranda,7.51,7.17,0.34,auralin,26u - 34u,26,34,hypoglycemia
15,elliot,richardson,7.56,7.09,0.47,novodra,40u - 45u,40,45,hypoglycemia
16,jasmine,sykes,7.56,7.18,0.38,novodra,42u - 44u,42,44,hypoglycemia
17,krisztina,magyar,7.52,7.01,0.51,novodra,32u - 27u,32,27,hypoglycemia
18,albinca,komavec,7.89,7.46,0.43,novodra,41u - 39u,41,39,hypoglycemia
19,ole,petersen,7.95,7.55,0.40,novodra,29u - 32u,29,32,hypoglycemia
20,abdul-nur,isa,7.98,7.53,0.45,novodra,54u - 50u,54,50,hypoglycemia
21,abel,yonatan,7.88,7.50,0.38,novodra,38u - 39u,38,39,cough
22,tegan,johnson,7.79,7.43,0.36,novodra,34u - 34u,34,34,headache
23,monika,lončar,9.13,8.72,0.41,novodra,49u - 46u,49,46,hypoglycemia
24,lena,baer,7.70,7.40,0.30,novodra,41u - 38u,41,38,hypoglycemia
25,cecilie,nilsen,9.63,9.21,0.42,novodra,49u - 50u,49,50,hypoglycemia
26,kang,mai,7.78,7.45,0.33,novodra,39u - 36u,39,36,injection site discomfort
27,leon,scholz,7.72,7.29,0.43,novodra,38u - 32u,38,32,injection site discomfort
28,steven,roy,7.87,7.43,0.44,novodra,41u - 43u,41,43,headache
29,miłosław,wiśniewski,7.51,7.08,0.43,novodra,34u - 33u,34,33,injection site discomfort
30,sofia,hermansen,8.90,8.57,0.33,novodra,34u - 34u,34,34,injection site discomfort
31,christopher,woodward,7.51,7.06,0.45,novodra,55u - 51u,55,51,nausea
32,lixue,hsueh,9.21,8.80,0.41,novodra,22u - 23u,22,23,injection site discomfort
33,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u,28,26,hypoglycemia
34,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u,42,44,injection site discomfort